apiVersion: v1
kind: Service
metadata:
  name: myemployees-service  
  labels:
    app.kubernetes.io/name: myemployees  
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: 8080  
    targetPort: 8080 
  selector:
    app.kubernetes.io/name: myemployees  
    app.kubernetes.io/component: frontend

