apiVersion: v1
kind: Service
metadata:
  name: employees-nodeport
spec:
  selector:
    app: employees
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  
  type: NodePort

