apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  containers:
    - name: mysql
      image: 469755524120.dkr.ecr.us-east-1.amazonaws.com/assigment-dev-mysql:v1.0
      imagePullPolicy: Always
      env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: employees
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      ports:
        - containerPort: 3306