apiVersion: v1
kind: Service
metadata:
  name: employeess-nodeport
  labels:
    app: employees
    version: v2
spec:
  selector:
    app: employees
    version: v2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 
  type: NodePort

